<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VersionPrefix>8.0.0</VersionPrefix>
    <PreReleaseVersionLabel>rtm</PreReleaseVersionLabel>
    <PreReleaseVersionIteration>
    </PreReleaseVersionIteration>
  </PropertyGroup>
  <PropertyGroup>
    <!-- dotnet/arcade -->
    <MicrosoftDotNetBuildTasksPackagingVersion>8.0.0-beta.26168.3</MicrosoftDotNetBuildTasksPackagingVersion>
    <!-- dotnet/cpython -->
    <runtimeosxarm64MicrosoftNETCoreRuntimeWasmPythonTransportVersion>8.0.0-rtm.26159.3</runtimeosxarm64MicrosoftNETCoreRuntimeWasmPythonTransportVersion>
    <runtimeosxx64MicrosoftNETCoreRuntimeWasmPythonTransportVersion>8.0.0-rtm.26159.3</runtimeosxx64MicrosoftNETCoreRuntimeWasmPythonTransportVersion>
    <runtimewinarm64MicrosoftNETCoreRuntimeWasmPythonTransportVersion>8.0.0-rtm.26159.3</runtimewinarm64MicrosoftNETCoreRuntimeWasmPythonTransportVersion>
    <runtimewinx64MicrosoftNETCoreRuntimeWasmPythonTransportVersion>8.0.0-rtm.26159.3</runtimewinx64MicrosoftNETCoreRuntimeWasmPythonTransportVersion>
  </PropertyGroup>
</Project>
